package com.ticketblitz.common.constant;

/**
 * BOOKING LIFECYCLE
 *
 * PENDING -> User reserved seats, payment not started
 * RESERVED -> Payment processing started
 * CONFIRMED -> Payment successful, booking complete
 * FULFILLED -> Tickets generated by fulfillment service
 * CANCELLED -> User cancelled or timeout
 * FAILED -> Payment failed
 *
 * @author Akhil
 */
public enum BookingStatus {
    PENDING,
    RESERVED,
    CONFIRMED,
    FULFILLED,
    CANCELLED,
    FAILED
}